---
- name: Create Instance
  ec2: > 
   region="{{ region }}"
   zone="{{ zone }}"
   id="{{ id + '_' + type }}"
   ec2_access_key="{{ ec2_access_key }}"
   ec2_secret_key="{{ ec2_secret_key }}"
   keypair="{{ keypair }}"
   instance_type="{{ instance_type }}"
   image="{{ image }}"
   group="{{ group }}"
   wait=true
   user_data="{{ type }}"
   instance_tags='{"type":"{{ type }}", "id":"{{ id }}"}'
   count="{{ ncount }}"
  register: ec2

- pause: seconds=60
  when: type == 'nodes'

- name: Add new instance to host group 
  add_host: hostname={{ item.public_dns_name }} groupname={{ type }}
  with_items: ec2.instances
  when: type != 'mq'

- name: Add new instance to host group 
  add_host: hostname={{ item.public_dns_name }} groupname="mq,mongo_servers"
  with_items: ec2.instances
  when: type == 'mq'
