---
- name: install and start apache
  hosts: webservers
  user: root

  tasks:

  - name: install httpd
    yum: name=httpd state=present

  - name: start httpd
    service: name=httpd state=running
