- hosts: localhost
  connection: local
  pre_tasks:
   - fail: msg=" Please make sure the variables  id is specified and unique in the command line -e id=uniquedev1"
     when: id is not defined
   
  roles: 
   - role: ec2_remove 
     type: dns 
     ncount: 1
   
   - role: ec2_remove
     type: mq 
     ncount: 3
   
   - role: ec2_remove
     type: broker
     ncount: 2
   
   - role: ec2_remove
     type: nodes
     ncount: "{{ count }}"
  
